feature_selection_mode: true  # 是否启用特征工程自动组合评测功能

output_subdir: car  # 以模型为文件名
auto_output_subdir: true  # 是否根据  模型类型 分段建模列 自动拼接output_subdir

# 数据配置
data:
  train_path: ./data/car/used_car_train_20200313.csv
  test_path: ./data/car/used_car_testB_20200421.csv
  preprocess_module: data/car/pre/feature_blocks.py  # 特征工程/预处理模块路径 
  clean_module: data/car/pre/clean_data.py  # 数据清洗模块路径
  val_path: null

# 输出目录配置
output:
  models_dir: models/
  predictions_dir: predictions/
  images_dir: images/


# 预测属性配置
prediction_column: price  # 预测的目标属性名，如 price 
# 唯一ID属性配置
id_column: SaleID  # 数据唯一ID字段名，如 SaleID 


# 模型配置
model:
  type: lightgbm  # 可选：xgboost, catboost, lightgbm
  params:
    common:
      n_estimators: [100]  # 弱学习器（树）的数量
      learning_rate: [0.2]  # 学习率，步长收缩系数
      random_state: [42]
    xgboost:
      objective: ["reg:squarederror"]  # 目标函数，回归任务用'reg:squarederror'，二分类用'binary:logistic'
      eval_metric: ["mae"]  # 评估指标，回归常用'rmse'/'mae'，二分类常用'auc'/'logloss'
      max_depth: [10]  # 树的最大深度
      colsample_bytree: [0.8]  # 每棵树随机采样的特征比例
      subsample: [0.8]  # 每棵树随机采样的样本比例
      alpha: [0.5]  # L1正则化系数
      lambda: [1]  # L2正则化系数
    lightgbm:
      subsample_freq: [8]  # bagging的次数
      num_leaves: [31]  # 一棵树上的最大叶子数
    catboost:
      depth: [6]  # 树的深度


# 交叉验证配置
cross_validation:
  enabled: false
  n_splits: 5

# 分段建模配置
segmentation:
  enabled: false
  segment_col: car_age
  n_bins: 5

# 脚本配置
scripts:
  # 主流程用到的模型和结果路径
  segment_model_path: models/segment_model.pkl  # 分段建模模型保存路径
  train_pred_path: predictions/train_pred.csv   # 训练集预测结果保存路径
  feature_importance_path: images/feature_importance.png  # 特征重要性图保存路径

# 特征工程配置
features:
  enable_print: false  # 控制是否显示print内容
  top_n_features: null  # 特征选择数量，null表示使用所有特征

# 缓存配置
cache:
  param_cache_path: ./cache/param_cache.json  # 参数调优缓存文件路径 

